#!/bin/bash

search_for() {
    for file in "$@"; do
        if [ -d "$file" ]; then
            search_for "$file"/*
        fi
        if [ -L "$file" ]; then
            if [[ !( -e "$file") ]]; then
                echo "Broken: $file"
            fi
        fi
    done
}

search_for "$@"
