#!/bin/bash

for file_name in "$@"; do
    if [ -f "$file_name" ]; then
        echo -n "New name for \"$file_name\" (empty - don't rename): "
        read -e new_file_name
        if [ -n "$new_file_name" ]; then
            mv "$file_name" "$new_file_name"
        fi
    fi
done

